name: ticksave
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

# AQUÍ ES DONDE SE PONEN LAS LIBRERÍAS
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^5.0.0  # <--- Aquí es donde debe ir, alineado con los de arriba
  # Núcleo de Firebase: inicialización y configuración
  firebase_core: ^4.5.0
  # Autenticación de usuarios (email/contraseña, Google, etc.)
  firebase_auth: ^6.2.0
  google_sign_in: any
  # Base de datos Cloud Firestore para guardar tickets y alertas
  cloud_firestore: ^6.1.3
  # Storage para guardar las imagenes de los tickets
  firebase_storage: any
  # Camara, OCR y Fechas
  image_picker: any
  flutter_image_compress: any
  google_mlkit_text_recognition: any
  intl: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # No pongas nada más debajo de aquí a menos que sean assets o fuentes