name: ticksave
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

# AQUÍ ES DONDE SE PONEN LAS LIBRERÍAS
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^5.0.0  # <--- Aquí es donde debe ir, alineado con los de arriba

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # No pongas nada más debajo de aquí a menos que sean assets o fuentes