// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANx66zsejIg_4KIu3sm_a4vV3aceXm6wg',
    appId: '1:272225874893:web:7fd3e56c36e629b19e8a84',
    messagingSenderId: '272225874893',
    projectId: 'ticksave-d8abd',
    authDomain: 'ticksave-d8abd.firebaseapp.com',
    storageBucket: 'ticksave-d8abd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu3l24tRfwczlbjVd_X4AP_2bh6k9jcf0',
    appId: '1:272225874893:android:d2029dd4d51a51079e8a84',
    messagingSenderId: '272225874893',
    projectId: 'ticksave-d8abd',
    storageBucket: 'ticksave-d8abd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvp2H0UsYfYHbDmzk47cdazyA63etU1S8',
    appId: '1:272225874893:ios:c6ce703caba62ebc9e8a84',
    messagingSenderId: '272225874893',
    projectId: 'ticksave-d8abd',
    storageBucket: 'ticksave-d8abd.firebasestorage.app',
    iosBundleId: 'com.example.ticksave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvp2H0UsYfYHbDmzk47cdazyA63etU1S8',
    appId: '1:272225874893:ios:c6ce703caba62ebc9e8a84',
    messagingSenderId: '272225874893',
    projectId: 'ticksave-d8abd',
    storageBucket: 'ticksave-d8abd.firebasestorage.app',
    iosBundleId: 'com.example.ticksave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANx66zsejIg_4KIu3sm_a4vV3aceXm6wg',
    appId: '1:272225874893:web:feeb2b8852e107ee9e8a84',
    messagingSenderId: '272225874893',
    projectId: 'ticksave-d8abd',
    authDomain: 'ticksave-d8abd.firebaseapp.com',
    storageBucket: 'ticksave-d8abd.firebasestorage.app',
  );
}
